package com.spring.fsms.member.dto;

public class MemberDto {

//	CREATE TABLE MEMBER (
//			MEMBER_ID 	VARCHAR(50) PRIMARY KEY,
//			MEMBER_NAME VARCHAR(50),
//			PASSWORD  VARCHAR(1000),
//			GENDER	VARCHAR(10),
//			DATE_BIRTH VARCHAR(30),
//			HP 	VARCHAR(30),
//			SMSSTS_YN  VARCHAR(30),
//			EMAIL VARCHAR(100),
//			EMAILSTS_YN VARCHAR(30),
//			ZIPCODE VARCHAR(50),
//			ROAD_ADDRESS VARCHAR(500),
//			JIBUN_ADDRESS VARCHAR(500),
//			NAMUJI_ADDRESS VARCHAR(500),
//			POINT	INT,
//			JOIN_DT DATE

//		)
}
